### ISSUE TITLE
Program crashes after a long run

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-filters#27]
After running RaTA one night, the system crashed and gave this traceback:

Traceback (most recent call last):
  File "./filters.py", line 75, in <module>
    mainloop(options)
  File "/home/ratadns/ratadns-filters-blanco/core.py", line 65, in mainloop
    fun(packet)
  File "/home/ratadns/ratadns-filters-blanco/prers/qnamecounter.py", line 34, in __call__
    qname = p.qname
  File "/home/ratadns/ratadns-filters-blanco/core.py", line 154, in qname
    return self.query['qname'].lower()
  File "/home/ratadns/ratadns-filters-blanco/core.py", line 178, in query
    return self._input['queries'][0]
IndexError: list index out of range

**Comment by franchoco** [comment]
Some logs:

[ratadns@dev-niclabs ratadns-filters-beauchef]$ cat tcpdump.err.log 
tcpdump: WARNING: em3: no IPv4 address assigned
tcpdump: listening on em3, link-type EN10MB (Ethernet), capture size 65535 bytes
3936229 packets captured
3936253 packets received by filter
22 packets dropped by kernel

The parser didn't give any output to the stderr

ratadns-filters-beauchef]$ tail -c 2000 beauchef.log 
lass":"1","ns":["dnsadmin.nic.cl.","a.nic.cl."]},{"name":"cl.","type":"6","class":"1","ns":["dnsadmin.nic.cl.","a.nic.cl."]},{"name":"cl.","type":"6","class":"1","ns":["dnsadmin.nic.cl.","a.nic.cl."]}]}134{"source":"be99b414","dest":"c8107010","id":"3954","flags":"10","queries":[{"qname":"mail.puertomontt.cl.","qtype":"1","qclass":"1"}]}129{"source":"be62e3ca","dest":"c8107010","id":"a180","flags":"10","queries":[{"qname":"mangacorta.cl.","qtype":"2b","qclass":"1"}]}627{"source":"c8107010","dest":"be62e3ca","id":"a180","flags":"8410","queries":[{"qname":"mangacorta.cl.","qtype":"2b","qclass":"1"}],"authorities":[{"name":"UQMLLOH4RHM0OJ9MU6UQU8N3KSONUS59.cl.","type":"32","class":"1","ns":[]},{"name":"UQMLLOH4RHM0OJ9MU6UQU8N3KSONUS59.cl.","type":"32","class":"1","ns":[]},{"name":"UQMLLOH4RHM0OJ9MU6UQU8N3KSONUS59.cl.","type":"32","class":"1","ns":[]},{"name":"UQMLLOH4RHM0OJ9MU6UQU8N3KSONUS59.cl.","type":"32","class":"1","ns":[]},{"name":"UQMLLOH4RHM0OJ9MU6UQU8N3KSONUS59.cl.","type":"32","class":"1","ns":[]},{"name":"UQMLLOH4RHM0OJ9MU6UQU8N3KSONUS59.cl.","type":"32","class":"1","ns":[]}]}747{"source":"c8107010","dest":"be99b414","id":"3954","flags":"8010","queries":[{"qname":"mail.puertomontt.cl.","qtype":"1","qclass":"1"}],"authorities":[{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]},{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]},{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]},{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]},{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]},{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]},{"name":"puertomontt.cl.","type":"2","class":"1","ns":["host.proexsi-internet.cl."]}]}128{"source":"be087721","dest":"c8107010","id":"97a3","flags":"10","queries":[{"qname":"ww5.indexa.cl.","qtype":"1","qclass":"1"}]}560{"source":"c810[

So, somewhere in the parser we are not doing things correctly.

**Comment by franchoco** [comment]
Is there any update on this?

**Comment by franchoco** [comment]
Solved with #43 .
